[package]
name = "hello-rust"
version = "0.1.0"
authors = ["asutorufa <16442314+Asutorufa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
url = "2.2.2"